  cout << q.getSize() << endl;
    q.push(20);
    cout << q.getSize() << endl;
    q.push(30);
    cout << q.getSize() << endl;
    q.push(40);
    cout << q.getSize() << endl;
    q.push(50);
    cout << q.getSize() << endl;
    q.push(60);
    cout << q.getSize() << endl;
    q.push(70);
    cout << q.getSize() << endl;
    cout << q.front() << endl;
    q.pop();
    q.pop();
    q.pop();
    cout << q.front() << endl;
    cout << q.getSize() << endl;
    cout << q.isEmpty() << endl;